### PR TITLE
Adding ability to work with Iceberg v1/v2

### PR DESCRIPTION
**Pull request by hpasumarthi**
## Describe your changes
Hello Team,
We have added the following code changes 
* ability to create iceberg table e.g  `stored by iceberg ` will be inserted if `is_iceberg` is set to true
* file_format variable `{{ file_format_clause() }}` was at a wrong order causing issues fixed it. 
* Merge logic has been enhanced to handle multiple unique keys which merging https://github.com/hpasumarthi/dbt-hive/blob/icebergV2/dbt/include/hive/macros/materializations/incremental/strategies.sql#L61 
* added featured to columns if the merge logic is not matched. https://github.com/hpasumarthi/dbt-hive/blob/icebergV2/dbt/include/hive/macros/materializations/incremental/strategies.sql#L90 

## Internal Jira ticket number or external issue link
https://jira.cloudera.com/browse/DBT-670 

## Testing procedure/screenshots(if appropriate):
* We have tested it internally 
## Checklist before requesting a review
- [ Yes] I have performed a self-review of my code
- [Notsure] I have formatted my added/modified code to follow pep-8 standards
- [ Yes] I have checked suggestions from python linter to make sure code is of good quality.

### CODE REVIEW

**Comment by tovganesh** [comment]
@hpasumarthi kindly attach screenshot of test output

**Comment by hpasumarthi** [comment]
Hi @tovganesh, 
Our test covers 
* ability to pass is_iceberg config to create iceberg table 
* ability to set table properties to set iceberg version 2 
* ability to merge and update columns matches mentioned as per config merge_update_columns 
* ability to merge and insert if columns does not match as per config merge_insert_columns 

Please find screenshots attached here 

* dbt code
 
Screenshot 2023-02-28 at 18 59 44

* dbt run execution 

Screenshot 2023-02-28 at 19 00 01

* dbt.log which show the create statement

Screenshot 2023-02-28 at 19 00 29
 
 * show create table output 
Screenshot 2023-02-28 at 19 00 44

Screenshot 2023-02-28 at 19 00 53

* table select * output 

Screenshot 2023-02-28 at 19 01 01

**Comment by tovganesh** [comment]
Looks good to me

**Review by tovganesh — APPROVED** [review]

**Review by myloginid — APPROVED** [review]
Approving the change

**Review by myloginid — APPROVED** [review]
Second Review

**Comment by hpasumarthi** [comment]
Hi @tovganesh  Can you guide us how we have new release 1.3.2 with the new code?

**Comment by tovganesh** [comment]
Update version numbers see https://github.com/cloudera/dbt-hive/pull/88
Also you should not be checking in .env file as mentioned above. 
Build and upload pip package (https://pypi.org/project/dbt-hive/)

**Pull request merged**
